# Generated by Django 4.1 on 2022-08-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=50)),
                ('option1_vote', models.IntegerField(default=0)),
                ('option2', models.CharField(max_length=50)),
                ('option2_vote', models.IntegerField(default=0)),
                ('option3', models.CharField(max_length=50)),
                ('option3_vote', models.IntegerField(default=0)),
                ('option4', models.CharField(max_length=50)),
                ('option4_vote', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
        ),
    ]
